services:
  stats-server:
    build: stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    environment:
        - POSTGRES_PASSWORD=stats
        - POSTGRES_USER=stats
        - POSTGRES_DB=stats
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stats -d stats" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  ewm-service:
    build: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
        ewm-db:
          condition: service_healthy
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - SPRING_LIQUIBASE_ENABLED=true
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - SPRING_DATASOURCE_INITIALIZATION_ORDER=before_hibernate
        - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=120000
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
        - SPRING_DATASOURCE_USERNAME=main
        - SPRING_DATASOURCE_PASSWORD=main
        - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    environment:
        - POSTGRES_PASSWORD=main
        - POSTGRES_USER=main
        - POSTGRES_DB=main
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U main -d main && psql -U main -d main -c 'SELECT 1'" ]
      interval: 5s
      timeout: 10s
      retries: 20
    ports:
      - "5433:5432"
